version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    command: server /data
    container_name: 'minio'
    ports:
    - '9001:9000'
    volumes:
    - ./data/minio:/data
    environment:
      MINIO_ACCESS_KEY: 'minio'
      MINIO_SECRET_KEY: 'minio123'

  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    ports:
    - '3306:3306'
    volumes:
    - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: hive
      MYSQL_PASSWORD: h1v3
      MYSQL_DATABASE: metastore_db

  metastore:
    image: bitsondatadev/hive-metastore:latest
    container_name: metastore
    ports:
    - '9083:9083'
    depends_on:
    - mariadb
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    volumes:
    - ./metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro

  trino:
    image: trinodb/trino:361
    container_name: trino
    ports:
      - '8080:8080'
    depends_on:
      - metastore
    volumes:
    - ./trino/conf:/etc/trino