version: '3'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-08-13T21-54-44Z
    command: server /data --console-address ":9001"
    container_name: minio
    ports:
    - '9000:9000'
    - '9001:9001'
    volumes:
    - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'minio123'

  mariadb:
    image: 'mariadb:latest'
    hostname: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    hostname: hive-metastore
    image: bitsondatadev/hive-metastore:latest
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./metastore/metastore-site-mysql.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb

#  metastore:
#    image: hive-standalone-metastore:3.0.0
#    build:
#      context: ./metastore
#    hostname: metastore
#    container_name: metastore
#    ports:
#    - '9083:9083'
#    depends_on:
#    - postgres
#    - minio
#    environment:
#      METASTORE_DB_HOSTNAME: postgres
#    volumes:
#    - ./metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
#
  trino:
    image: trinodb/trino:393
    container_name: trino
    ports:
      - '8080:8080'
    depends_on:
      - metastore
    volumes:
    - ./trino/conf:/etc/trino
#  postgres:
#    image: postgres:14.4-alpine
#    container_name: postgres
#    restart: unless-stopped
#    environment:
#      - POSTGRES_USER=ff
#      - POSTGRES_PASSWORD=f4nt45y
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data